<script language="JScript" src="spec/core/BaseSpec.js" runat="server"></script>
<script language="JScript" src="spec/core/CustomMatchersSpec.js" runat="server"></script>
<script language="JScript" src="spec/core/EnvSpec.js" runat="server"></script>
<script language="JScript" src="spec/core/ExceptionsSpec.js" runat="server"></script>
<script language="JScript" src="spec/core/JsApiReporterSpec.js" runat="server"></script>
<script language="JScript" src="spec/core/MatchersSpec.js" runat="server"></script>
<script language="JScript" src="spec/core/MockClockSpec.js" runat="server"></script>
<script language="JScript" src="spec/core/MultiReporterSpec.js" runat="server"></script>
<script language="JScript" src="spec/core/NestedResultsSpec.js" runat="server"></script>
<script language="JScript" src="spec/core/PrettyPrintSpec.js" runat="server"></script>
<script language="JScript" src="spec/core/QueueSpec.js" runat="server"></script>
<script language="JScript" src="spec/core/ReporterSpec.js" runat="server"></script>
<script language="JScript" src="spec/core/RunnerSpec.js" runat="server"></script>
<script language="JScript" src="spec/core/SpecRunningSpec.js" runat="server"></script>
<script language="JScript" src="spec/core/SpecSpec.js" runat="server"></script>
<script language="JScript" src="spec/core/SpySpec.js" runat="server"></script>
<script language="JScript" src="spec/core/SuiteSpec.js" runat="server"></script>
<script language="JScript" src="spec/core/UtilSpec.js" runat="server"></script>
<script language="JScript" src="spec/core/WaitsForBlockSpec.js" runat="server"></script>