<script language="JScript" src="core/BaseSpec.js" runat="server"></script>
<script language="JScript" src="core/CustomMatchersSpec.js" runat="server"></script>
<script language="JScript" src="core/EnvSpec.js" runat="server"></script>
<script language="JScript" src="core/ExceptionsSpec.js" runat="server"></script>
<script language="JScript" src="core/JsApiReporterSpec.js" runat="server"></script>
<script language="JScript" src="core/MatchersSpec.js" runat="server"></script>
<script language="JScript" src="core/MockClockSpec.js" runat="server"></script>
<script language="JScript" src="core/MultiReporterSpec.js" runat="server"></script>
<script language="JScript" src="core/NestedResultsSpec.js" runat="server"></script>
<script language="JScript" src="core/PrettyPrintSpec.js" runat="server"></script>
<script language="JScript" src="core/QueueSpec.js" runat="server"></script>
<script language="JScript" src="core/ReporterSpec.js" runat="server"></script>
<script language="JScript" src="core/RunnerSpec.js" runat="server"></script>
<script language="JScript" src="core/SpecRunningSpec.js" runat="server"></script>
<script language="JScript" src="core/SpecSpec.js" runat="server"></script>
<script language="JScript" src="core/SpySpec.js" runat="server"></script>
<script language="JScript" src="core/SuiteSpec.js" runat="server"></script>
<script language="JScript" src="core/UtilSpec.js" runat="server"></script>
<script language="JScript" src="core/WaitsForBlockSpec.js" runat="server"></script>